/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudemployee;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RetrieveData extends javax.swing.JFrame {

    /**
     * Creates new form RetrieveData
     */
    public RetrieveData() {
        initComponents();
        getdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addEmployeeButton = new javax.swing.JButton();
        editDetails = new javax.swing.JButton();
        deleteDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idNumber", "firstName", "middleName", "lastName", "gender", "mobileNumber", "emailAddress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        addEmployeeButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addEmployeeButton.setForeground(new java.awt.Color(0, 0, 102));
        addEmployeeButton.setText("ADD EMPLOYEE");
        addEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeButtonMouseClicked(evt);
            }
        });
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        editDetails.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        editDetails.setForeground(new java.awt.Color(0, 0, 102));
        editDetails.setText("EDIT");
        editDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editDetailsMouseClicked(evt);
            }
        });
        editDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDetailsActionPerformed(evt);
            }
        });

        deleteDetails.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        deleteDetails.setForeground(new java.awt.Color(0, 0, 102));
        deleteDetails.setText("DELETE");
        deleteDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteDetailsMouseClicked(evt);
            }
        });
        deleteDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(571, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEmployeeButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editDetails)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDetails)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addEmployeeButton)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 86, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeButtonMouseClicked


    }//GEN-LAST:event_addEmployeeButtonMouseClicked

    private void editDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editDetailsMouseClicked
      
    }//GEN-LAST:event_editDetailsMouseClicked

    private void deleteDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDetailsMouseClicked

    }//GEN-LAST:event_deleteDetailsMouseClicked

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
      new AddEmployee().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void editDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDetailsActionPerformed
       new EditEmployeeInfo().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_editDetailsActionPerformed

    private void deleteDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDetailsActionPerformed
      new DeleteEmployee().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_deleteDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetrieveData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetrieveData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetrieveData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetrieveData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetrieveData().setVisible(true);
            }
        });
    }
       public void getdata(){
       
       
         int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crudemployee", "root", "");
            Statement stmt = con.createStatement();
           
            ResultSet datas = stmt.executeQuery("select * from retrieveemployee");
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            while (datas.next()) {
                count = 1;
                model.addRow(new Object[]{datas.getInt("idNumber"), datas.getString("firstName"), datas.getString("middleName"), datas.getString("lastName"),datas.getString("gender"), datas.getString("mobileNumber"), datas.getString("emailAddress")});
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(null,"No data found!.","Alert",JOptionPane.WARNING_MESSAGE);  
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton deleteDetails;
    private javax.swing.JButton editDetails;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
